networks:
  payment-microservice-net:
    driver: bridge

services:
  payment-microservice-app:
    image: ${APP_NAME}:1.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${APP_PORT}
    container_name: ${APP_NAME}
    networks:
      - payment-microservice-net
    depends_on:
      payment-microservice-mongodb:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: always
    command: bash -c "./config/init_db/init_db.sh && poetry run uvicorn src.app:app --host 0.0.0.0 --port ${APP_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  payment-microservice-mongodb:
    image: mongo:${MONGO_VERSION:-7.0}
    container_name: ${MONGO_CONTAINER_NAME:-mongodb}
    restart: always
    networks:
      - payment-microservice-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - payment-microservice-mongodb-data:/data/db
      - payment-microservice-mongodb-config:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  payment-microservice-mongodb-data:
  payment-microservice-mongodb-config:
